#!/bin/sh

# iptables rules must be applied at runtime
if ! [ -f iptables.rules ]; then
    echo "ERRROR: Firewall rules missing!"
    exit 255
fi
iptables-restore < iptables.rules || echo "WARNING: Failed to apply firewall rules!"
exit 0